// Get currency list constants
export const FETCH_CURRENCY_SUCCESS = 'FETCH_CURRENCY_SUCCESS';
export const FETCH_CURRENCY_ERROR = 'FETCH_CURRENCY_ERROR';

export const ADD_CURRENCY_PAIR = 'ADD_CURRENCY_PAIR';
export const REMOVE_CURRENCY_PAIR = 'REMOVE_CURRENCY_PAIR';
export const CHANGE_CURRENCY_PAIR = 'CHANGE_CURRENCY_PAIR';

export const LOADING_COMPLETE = 'LOADING_COMPLETE';
export const LOADING_ERROR = 'LOADING_ERROR';
