// Get currency list constants
export const FETCH_CURRENCY_SUCCESS = 'FETCH_CURRENCY_SUCCESS';
export const FETCH_CURRENCY_ERROR = 'FETCH_CURRENCY_ERROR';

export const TOP_SELECTOR_ONE = 'TOP_SELECTOR_CHANGE_ONE';
export const TOP_SELECTOR_TWO = 'TOP_SELECTOR_CHANGE_TWO';
export const BOTTOM_SELECTOR_ONE = 'BOTTOM_SELECTOR_ONE';
export const BOTTOM_SELECTOR_TWO = 'BOTTOM_SELECTOR_TWO';

